/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Deber_03_05.Vista;

import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Juano
 */
public class Ventana_Principal extends javax.swing.JFrame {

    private Ventana_Pelicula_Crear ventanaPeliculaCrear;
    private Ventana_Pelicula_Modificar ventanaPeliculaModificar;
    private Ventana_Pelicula_Eliminar ventanaPeliculaEliminar;
    private Ventana_Pelicula_Listar ventanaPeliculaListar;

    private Ventana_Actor_Crear ventanaActorCrear;
    private Ventana_Actor_Modificar ventanaActorModificar;
    private Ventana_Actor_Eliminar ventanaActorEliminar;
    private Ventana_Actor_Listar ventanaActorListar;

    private Ventana_Personaje_Crear ventanaPersonajeCrear;
    private Ventana_Personaje_Modificar ventanaPersonajeModificar;
    private Ventana_Personaje_Eliminar ventanaPersonajeEliminar;
    private Ventana_Personaje_Listar ventanaPersonajeListar;

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        jMenu1.setText("PELICULA");

        jMenuItem1.setText("Crear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Modicar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Eliminar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Listar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("ACTOR");

        jMenuItem5.setText("Crear");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Modicar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Eliminar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Listar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("PERSONAJE");

        jMenuItem9.setText("Crear");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setText("Modicar");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setText("Eliminar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem12.setText("Listar");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        this.ventanaPeliculaCrear = new Ventana_Pelicula_Crear();
        ventanaPeliculaCrear.setVisible(true);
        ventanaPeliculaCrear.setResizable(true);
        ventanaPeliculaCrear.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPeliculaCrear.setClosable(true);
        ventanaPeliculaCrear.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPeliculaCrear);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        this.ventanaPeliculaModificar = new Ventana_Pelicula_Modificar();
        ventanaPeliculaModificar.setVisible(true);
        ventanaPeliculaModificar.setResizable(true);
        ventanaPeliculaModificar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPeliculaModificar.setClosable(true);
        ventanaPeliculaModificar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPeliculaModificar);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        this.ventanaPeliculaEliminar = new Ventana_Pelicula_Eliminar();
        ventanaPeliculaEliminar.setVisible(true);
        ventanaPeliculaEliminar.setResizable(true);
        ventanaPeliculaEliminar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPeliculaEliminar.setClosable(true);
        ventanaPeliculaEliminar.setIconifiable(true);
        this.jDesktopPane1.add(this.ventanaPeliculaEliminar);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        this.ventanaPeliculaListar = new Ventana_Pelicula_Listar();
        ventanaPeliculaListar.setVisible(true);
        ventanaPeliculaListar.setResizable(true);
        ventanaPeliculaListar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPeliculaListar.setClosable(true);
        ventanaPeliculaListar.setIconifiable(true);
        this.jDesktopPane1.add(this.ventanaPeliculaListar);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.ventanaActorCrear = new Ventana_Actor_Crear();
        ventanaActorCrear.setVisible(true);
        ventanaActorCrear.setResizable(true);
        ventanaActorCrear.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaActorCrear.setClosable(true);
        ventanaActorCrear.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaActorCrear);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.ventanaActorModificar = new Ventana_Actor_Modificar();
        ventanaActorModificar.setVisible(true);
        ventanaActorModificar.setResizable(true);
        ventanaActorModificar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaActorModificar.setClosable(true);
        ventanaActorModificar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaActorModificar);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.ventanaActorEliminar = new Ventana_Actor_Eliminar();
        ventanaActorEliminar.setVisible(true);
        ventanaActorEliminar.setResizable(true);
        ventanaActorEliminar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaActorEliminar.setClosable(true);
        ventanaActorEliminar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaActorEliminar);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        this.ventanaActorListar = new Ventana_Actor_Listar();
        ventanaActorListar.setVisible(true);
        ventanaActorListar.setResizable(true);
        ventanaActorListar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaActorListar.setClosable(true);
        ventanaActorListar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaActorListar);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        this.ventanaPersonajeCrear = new Ventana_Personaje_Crear();
        ventanaPersonajeCrear.setVisible(true);
        ventanaPersonajeCrear.setResizable(true);
        ventanaPersonajeCrear.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPersonajeCrear.setClosable(true);
        ventanaPersonajeCrear.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPersonajeCrear);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        this.ventanaPersonajeModificar = new Ventana_Personaje_Modificar();
        ventanaPersonajeModificar.setVisible(true);
        ventanaPersonajeModificar.setResizable(true);
        ventanaPersonajeModificar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPersonajeModificar.setClosable(true);
        ventanaPersonajeModificar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPersonajeModificar);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        this.ventanaPersonajeEliminar = new Ventana_Personaje_Eliminar();
        ventanaPersonajeEliminar.setVisible(true);
        ventanaPersonajeEliminar.setResizable(true);
        ventanaPersonajeEliminar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPersonajeEliminar.setClosable(true);
        ventanaPersonajeEliminar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPersonajeEliminar);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        this.ventanaPersonajeListar = new Ventana_Personaje_Listar();
        ventanaPersonajeListar.setVisible(true);
        ventanaPersonajeListar.setResizable(true);
        ventanaPersonajeListar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPersonajeListar.setClosable(true);
        ventanaPersonajeListar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPersonajeListar);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
